#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{php,log/php}

# copy config files
[[ ! -f /config/nginx/nginx-fpm.conf ]] && \
    cp /defaults/nginx-fpm.conf /config/nginx/nginx-fpm.conf
cp /config/nginx/nginx-fpm.conf /etc/php5/php-fpm.conf

# fix timezone in php.ini
sed -i "s#date.timezone = .*#date.timezone = $TZ#g" /etc/php5/php.ini

